"""Business module schemas package."""
from app.modules.business.schemas.business import BusinessCreate, BusinessRead, BusinessUpdate
from app.modules.business.schemas.category import CategoryCreate, CategoryRead
from app.modules.business.schemas.product import ProductCreate, ProductRead, ProductUpdate
from app.modules.business.schemas.service import ServiceCreate, ServiceRead, ServiceUpdate
from app.modules.business.schemas.favorite import FavoriteCreate, FavoriteRead
from app.modules.business.schemas.inquiry import InquiryCreate, InquiryRead
from app.modules.business.schemas.api import (
    BusinessCreateRequest,
    BusinessUpdateRequest,
    BusinessResponse,
    BusinessListResponse,
    CategoryCreateRequest,
    CategoryUpdateRequest,
    CategoryResponse,
    CategoryListResponse,
    ProductCreateRequest,
    ProductUpdateRequest,
    ProductResponse,
    ProductListResponse,
    ServiceCreateRequest,
    ServiceUpdateRequest,
    ServiceResponse,
    ServiceListResponse,
    FavoriteCreateRequest,
    FavoriteResponse,
    FavoriteListResponse,
    InquiryCreateRequest,
    InquiryResponse,
    InquiryListResponse,
    InquiryStatusUpdate,
)

__all__ = [
    "BusinessCreate",
    "BusinessRead",
    "BusinessUpdate",
    "CategoryCreate",
    "CategoryRead",
    "ProductCreate",
    "ProductRead",
    "ProductUpdate",
    "ServiceCreate",
    "ServiceRead",
    "ServiceUpdate",
    "FavoriteCreate",
    "FavoriteRead",
    "InquiryCreate",
    "InquiryRead",
    "BusinessCreateRequest",
    "BusinessUpdateRequest",
    "BusinessResponse",
    "BusinessListResponse",
    "CategoryCreateRequest",
    "CategoryUpdateRequest",
    "CategoryResponse",
    "CategoryListResponse",
    "ProductCreateRequest",
    "ProductUpdateRequest",
    "ProductResponse",
    "ProductListResponse",
    "ServiceCreateRequest",
    "ServiceUpdateRequest",
    "ServiceResponse",
    "ServiceListResponse",
    "FavoriteCreateRequest",
    "FavoriteResponse",
    "FavoriteListResponse",
    "InquiryCreateRequest",
    "InquiryResponse",
    "InquiryListResponse",
    "InquiryStatusUpdate",
]